[env:sanzxcam]
board = sanzxcam
board_build.partitions = custom_8Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/sanzxcam>
build_flags =
	${env.build_flags}
	-Iboards/sanzxcam
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DSANZXCAM

	;TFT_eSPI Setup
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MOSI=45
	-DTFT_MISO=42
	-DTFT_SCLK=47
	-DTFT_DC=14
	-DTFT_CS=21
	-DTFT_RST=1
	-DTFT_BL=-1
	-DTFT_BACKLIGHT_ON=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000

	;Buttons configuration
	-DHAS_BTN=1
	-DSEL_BTN=0
	-DUP_BTN=41
	-DESC_BTN=3
	-DDW_BTN=46
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Ok"'

	-DDEVICE_NAME='"sanzxcam"'

lib_deps =
	${env.lib_deps}
